defaults: &defaults
  docker:
    - image: circleci/node:16-browsers
      environment:
        TZ: "Europe/Paris"
        JOBS: 1
  working_directory: ~/spa-ondemand-poc

version: 2

parameters:
  bucket_uri:
    type: string
    default: "devs3bucket"

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  # deploy-main:
  #   <<: *defaults
  #   environment:
  #     BUCKET_URI: "${bucket_uri}"
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - run:
  #         name: bucket selection S3
  #         command: echo $BUCKET_URI
  deploy-main:
    <<: *defaults
    steps:
    - attach_workspace:
        at: .
    - run:
        name: Set BUCKET_URI environment variable
        command: echo "BUCKET_URI=${pipeline.parameters.bucket_uri}" >> $BASH_ENV
    - run:
        name: Display BUCKET_URI
        command: |
          source $BASH_ENV
          echo $BUCKET_URI


workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - deploy-main:
          filters:
            branches:
              only: main
