defaults: &defaults
  docker:
    - image: circleci/node:16-browsers
      environment:
        TZ: "Europe/Paris"
        JOBS: 1
  working_directory: ~/spa-ondemand-poc

version: 2

parameters:
  bucket_uri:
    type: string
    default: "devs3bucket"

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy-main:
    <<: *defaults
    environment:
      BUCKET_URI: << pipeline.parameters.bucket_uri >>
    steps:
      - attach_workspace:
          at: .
      - run:
          name: bucket selection S3
          command: echo $BUCKET_URI
      - run:
          name: bucket from parameters
          command: echo << pipeline.parameters.bucket_uri >>


workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - deploy-main:
          filters:
            branches:
              only: main