defaults: &defaults
  docker:
    - image: circleci/node:16-browsers
      environment:
        TZ: "Europe/Paris"
        JOBS: 1
  working_directory: ~/spa-ondemand-poc

version: 2.1 # Use version 2.1 to enable Orb usage.

parameters:
  bucket_uri:
    type: boolean
    default: false
  deploy_to_prod:
    type: boolean
    default: false
    
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy-dev-main:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: bucket selection S3 - main dev bucket
          command: echo pwd
    
  deploy-prod-main:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: bucket selection S3 - main prod bucket
          command: echo date

workflows:
  build_and_test_prod:
    when:
      and:
        - equal: [true, << pipeline.parameters.deploy_to_prod >>] # true, false -  should not execute
    jobs:
      - deploy-prod-main:
          filters:
            branches:
              only: main

  build_and_test_dev:
    when:
      and:
        - equal: [false, << pipeline.parameters.deploy_to_prod >>] # false, false - should execute 
    jobs:
      - checkout_code
      - deploy-dev-main:
          filters:
            branches:
              only: main
