defaults: &defaults
  docker:
    - image: circleci/node:16-browsers
      environment:
        TZ: "Europe/Paris"
        JOBS: 1
  working_directory: ~/

version: 2
jobs:
  coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo "$CIRCLE_PULL_REQUEST" > _temp_circle_pull_request
      - restore_cache:
          keys:
            - coverage-comment-id-{{ checksum "_temp_circle_pull_request" }}
      - run:
          name: 'Generate coverage status'
          command: echo "yarn pipeline coverage status"
      - save_cache:
          when: always
          key: coverage-comment-id-{{ checksum "_temp_circle_pull_request" }}
          paths:
            - ~/github-coverage-comment-id
      - store_artifacts:
          path: ./coverage

  deploy-master:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Crowdin Upload
          command: echo "crowdin upload"
      - run:
          name: Crowdin Download
          command: echo "crowdin download"
      - run:
          name: Deploy
          command: echo "deploy dev"
workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
      - coverage:
          requires:
            - test
      - deploy-master:
          requires:
            - lint
            - test
          filters:
            branches:
              only: main
      - deploy-dev:
          requires:
            - lint
            - test
          filters:
            branches:
              only: dev
          