defaults: &defaults
  docker:
    - image: circleci/node:16-browsers
      environment:
        TZ: "Europe/Paris"
        JOBS: 1
  working_directory: ~/spa-ondemand-poc

# version: 2

# parameters:
#   bucket_uri:
#     type: string
#     default: $BUCKET_URI
#   trigger-job:
#     type: boolean
#     default: false

# jobs:
#   checkout_code:
#     <<: *defaults
#     steps:
#       - checkout
#       - persist_to_workspace:
#           root: .
#           paths:
#             - .

#   deploy-main:
#     <<: *defaults
#     parameters:
#       bucket_uri:
#         type: string
#         default: $BUCKET_URI
#     # environment:
#     #   BUCKET_URI: "${bucket_uri}"
#     steps:
#       - attach_workspace:
#           at: .
#       - run:
#           name: bucket selection S3
#           command: echo $BUCKET_URI | base64
#       - run:
#           name: Show Bucket URI
#           command: echo "<< parameters.bucket_uri >>"



# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - checkout_code
#       - deploy-main:
#           when:
#             and:
#             - equal: [true, << pipeline.parameters.trigger-job >>]
#           filters:
#             branches:
#               only: main


version: 2.1 # Use version 2.1 to enable Orb usage.

parameters:
  bucket_uri:
    type: boolean
    default: false
  trigger-job:
    type: boolean
    default: false
    
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy-main:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: bucket selection S3
          command: echo $BUCKET_URI | base64
      - run:
          name: Show Bucket URI
          command: echo "<< parameters.bucket_uri >>"  

workflows:
  build_and_test:
    when:
      and:
        - equal: [true, << pipeline.parameters.trigger-job >>]
    jobs:
      - checkout_code
      - deploy-main:
          filters:
            branches:
              only: main